<?php

namespace ContainerOxrmmKI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CdW1wBkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CdW1wBk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CdW1wBk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'config' => ['privates', 'App\\Service\\ConfigService', 'getConfigServiceService', false],
        ], [
            'config' => 'App\\Service\\ConfigService',
        ]);
    }
}
