<?php

namespace Container8CvcICH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BBNcfqTService extends App_KernelNcodedCommandDebugContainer
{
    /**
     * Gets the private '.service_locator.bBNcfqT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bBNcfqT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::config' => ['privates', '.service_locator.FgREIYJ', 'get_ServiceLocator_FgREIYJService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.yHobP0h', 'get_ServiceLocator_YHobP0hService', true],
            'App\\Controller\\SitemapController::robots' => ['privates', '.service_locator.CdW1wBk', 'get_ServiceLocator_CdW1wBkService', true],
            'App\\Controller\\SitemapController::sitemap' => ['privates', '.service_locator.CdW1wBk', 'get_ServiceLocator_CdW1wBkService', true],
            'App\\Controller\\ToolsController::getPhpCode' => ['privates', '.service_locator.FgREIYJ', 'get_ServiceLocator_FgREIYJService', true],
            'App\\Controller\\ToolsController::index' => ['privates', '.service_locator.FgREIYJ', 'get_ServiceLocator_FgREIYJService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\AdminController:config' => ['privates', '.service_locator.FgREIYJ', 'get_ServiceLocator_FgREIYJService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.yHobP0h', 'get_ServiceLocator_YHobP0hService', true],
            'App\\Controller\\SitemapController:robots' => ['privates', '.service_locator.CdW1wBk', 'get_ServiceLocator_CdW1wBkService', true],
            'App\\Controller\\SitemapController:sitemap' => ['privates', '.service_locator.CdW1wBk', 'get_ServiceLocator_CdW1wBkService', true],
            'App\\Controller\\ToolsController:getPhpCode' => ['privates', '.service_locator.FgREIYJ', 'get_ServiceLocator_FgREIYJService', true],
            'App\\Controller\\ToolsController:index' => ['privates', '.service_locator.FgREIYJ', 'get_ServiceLocator_FgREIYJService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\AdminController::config' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SitemapController::robots' => '?',
            'App\\Controller\\SitemapController::sitemap' => '?',
            'App\\Controller\\ToolsController::getPhpCode' => '?',
            'App\\Controller\\ToolsController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:config' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SitemapController:robots' => '?',
            'App\\Controller\\SitemapController:sitemap' => '?',
            'App\\Controller\\ToolsController:getPhpCode' => '?',
            'App\\Controller\\ToolsController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
