<?php

namespace Container8CvcICH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YHobP0hService extends App_KernelNcodedCommandDebugContainer
{
    /**
     * Gets the private '.service_locator.yHobP0h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yHobP0h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'config' => ['privates', 'App\\Service\\ConfigService', 'getConfigServiceService', true],
        ], [
            'authenticationUtils' => '?',
            'config' => 'App\\Service\\ConfigService',
        ]);
    }
}
