<?php

namespace Container8CvcICH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigServiceService extends App_KernelNcodedCommandDebugContainer
{
    /**
     * Gets the private 'App\Service\ConfigService' shared autowired service.
     *
     * @return \App\Service\ConfigService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ConfigService.php';

        return $container->privates['App\\Service\\ConfigService'] = new \App\Service\ConfigService(($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
