<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8CvcICH\App_KernelNcodedCommandDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8CvcICH/App_KernelNcodedCommandDebugContainer.php') {
    touch(__DIR__.'/Container8CvcICH.legacy');

    return;
}

if (!\class_exists(App_KernelNcodedCommandDebugContainer::class, false)) {
    \class_alias(\Container8CvcICH\App_KernelNcodedCommandDebugContainer::class, App_KernelNcodedCommandDebugContainer::class, false);
}

return new \Container8CvcICH\App_KernelNcodedCommandDebugContainer([
    'container.build_hash' => '8CvcICH',
    'container.build_id' => '955a938c',
    'container.build_time' => 1732265026,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8CvcICH');
