<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxrmmKI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxrmmKI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxrmmKI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxrmmKI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxrmmKI\App_KernelDevDebugContainer([
    'container.build_hash' => 'OxrmmKI',
    'container.build_id' => 'ba272735',
    'container.build_time' => 1756807869,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxrmmKI');
